site_name: notes.anyvoid.dev
site_url: https://notes.anyvoid.dev
site_description: Notes de cours en informatique, automatisme, traitement du signal et électronique.
site_author: Nicolas Mugnier

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

nav:
  - Accueil: index.md
  - Bases de données:
    - Conception d'un schéma relationnel: bases-de-donnees/conception-schema-relationnel.md
    - Formes normales: bases-de-donnees/formes-normales.md
  - Traitement du signal:
    - Transformée de Fourier: traitement-du-signal/transformee-de-fourier.md
